# Generated by Django 5.0.3 on 2024-04-05 00:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fitness_trainers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnesstrainer',
            name='trainer',
            field=models.OneToOneField(limit_choices_to={'user_role': 'Trainer'}, on_delete=django.db.models.deletion.PROTECT, related_name='fitness_trainer', to=settings.AUTH_USER_MODEL),
        ),
    ]
