# Generated by Django 5.0.3 on 2024-04-05 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_trainers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
